<!DOCTYPE html>
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>有源pt 影视中心</title>
  
  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="../stylesheets/foundation.css">
  -->
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="/public/foundation/stylesheets/foundation.min.css">
  <link rel="stylesheet" href="/public/home/stylesheets/login.css">
  <link rel="stylesheet" href="/public/foundation/font/css/font-awesome.css">

  <script src="/public/foundation/javascripts/modernizr.foundation.js"></script>
  <script src="/public/home/javascripts/jquery.js"></script>
  <script src="/public/foundation/javascripts/foundation.min.js"></script>
  <script src="/public/home/javascripts/jsjquery.verification.js"></script>
</head>
<body>
  <div class="login row">
    <div class="background">
      <img src="/public/home/images/logo.png" />
    </div>
    <div class="signup">还没有有源账号？<a href="/signup">立即注册</a></div>
    <form id="login" class="login-form" method="post">
      <div id="user">
        <span class="title">账号：</span>
        <input type="text" name="name">
      </div>
      <div id="password">
        <span class="title">密码：</span>
        <input type="password" name="userpass">
      </div>
      <div>
        <span class="right">
          <a href="#">忘记密码?</a>
        </span>
      </div>
      <div class="submit">
        <input type="submit" id="loginbutton" class="button" value="登录">
      </div>
    </form>
  </div>
  <!-- Initialize JS Plugins -->
  <script src="/public/home/javascripts/app.js"></script>
  <?php if($errors):?>
    <div id="msg-tip" class="reveal-modal tiny">
      <div class="msg">
        <div class="title">提示</div>
        <div class="content"><?php echo $errors;?></div>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>
    <script type='text/javascript'>
      $("#msg-tip").reveal("open");
    </script>
  <?php endif;?>
</body>
</html>
