<!DOCTYPE html>
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>有源pt 影视中心</title>
  
  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="../stylesheets/foundation.css">
  -->
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="/public/foundation/stylesheets/foundation.min.css">
  <link rel="stylesheet" href="/public/home/stylesheets/signup.css">
  <link rel="stylesheet" href="/public/foundation/font/css/font-awesome.css">

  <script src="/public/foundation/javascripts/modernizr.foundation.js"></script>
  <script src="/public/home/javascripts/jquery.js"></script>
  <script src="/public/home/javascripts/jsjquery.verification.js"></script>
</head>
<body>
   <div class="signup row">
    <div class="background">
      <img src="/public/home/images/logo.png" />
    </div>
    <div class="tologin">已经有有源账号？<a href="/login">立即登录</a></div>
    <form id="signup" class="signup-form" method="post">
      <div id="user">
        <span class="title"><i>*</i>账号：</span>
        <input type="text" name="name">
        <span class='red' id='user_tips'></span>
      </div>
      <div id="password">
        <span class="title"><i>*</i>设置密码：</span>
        <input type="password" name="userpass">
        <span class='red' id='pass_tips'></span>
      </div>
      <div id="mail">
        <span class="title"><i>*</i>邮件：</span>
        <input type="text" name="mail" value="">
        <span class='red' id='mail_tips'></span>
      </div>
      <div id="required">
        <span class="title"><i>*</i>邀请码：</span>
        <input type="text" name="invitenumber">
      </div>
      <div class="submit">
        <input type="submit" id = "signupbutton" class="button" value="立即注册">
      </div>
    </form>
  </div>

  <?php if($errors):?>
    <div id="msg-tip" class="reveal-modal tiny">
      <div class="msg">
        <div class="title">提示</div>
        <div class="content"><?php echo $errors;?></div>
      </div>
      <a class="close-reveal-modal">&#215;</a>
    </div>
    <script type='text/javascript'>
      $("#msg-tip").reveal("open");
    </script>
  <?php endif;?>

  <!-- Included JS Files (Uncompressed) -->
  <!--
  
  <script src="javascripts/jquery.js"></script>
  
  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>
  
  <script src="javascripts/jquery.foundation.forms.js"></script>
  
  <script src="javascripts/jquery.foundation.reveal.js"></script>
  
  <script src="javascripts/jquery.foundation.orbit.js"></script>
  
  <script src="javascripts/jquery.foundation.navigation.js"></script>
  
  <script src="javascripts/jquery.foundation.buttons.js"></script>
  
  <script src="javascripts/jquery.foundation.tabs.js"></script>
  
  <script src="javascripts/jquery.foundation.tooltips.js"></script>
  
  <script src="javascripts/jquery.foundation.accordion.js"></script>
  
  <script src="javascripts/jquery.placeholder.js"></script>
  
  <script src="javascripts/jquery.foundation.alerts.js"></script>
  
  -->
  
  <!-- Included JS Files (Compressed) -->
  <script src="/public/home/javascripts/jquery.js"></script>
  <script src="/public/foundation/javascripts/foundation.min.js"></script>
  
  <!-- Initialize JS Plugins -->
  <script src="/public/home/javascripts/app.js"></script>
</body>
</html>
