<!DOCTYPE html>
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>有源pt 影视中心</title>
  
  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="../stylesheets/foundation.css">
  -->
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="/public/home/stylesheets/foundation.min.css">
  <link rel="stylesheet" href="/public/home/stylesheets/login.css">
  <link rel="stylesheet" href="/public/home/font/css/font-awesome.css">

  <script src="/public/home/javascripts/modernizr.foundation.js"></script>
  <script src="/public/home/javascripts/jquery.js"></script>
  <script src="/public/home/javascripts/jsjquery.verification.js"></script>
</head>
<body>
  <div class="login row">
    <div class="background">
      <img src="/public/home/images/logo.png" />
    </div>
    <div class="signup">还没有有源账号？<a href="/signup">立即注册</a></div>
    <form id="login" class="login-form" method="post">
      <div id="user">
        <span class="title">账号：</span>
        <input type="text" name="name">
      </div>
      <div id="password">
        <span class="title">密码：</span>
        <input type="password" name="userpass">
      </div>
      <div>
        <span class="right">
          <a href="#">忘记密码?</a>
        </span>
      </div>
      <div class="submit">
        <input type="submit" id="loginbutton" class="button" value="登录">
      </div>
    </form>
  </div>




  <!-- Included JS Files (Uncompressed) -->
  <!--
  
  <script src="javascripts/jquery.js"></script>
  
  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>
  
  <script src="javascripts/jquery.foundation.forms.js"></script>
  
  <script src="javascripts/jquery.foundation.reveal.js"></script>
  
  <script src="javascripts/jquery.foundation.orbit.js"></script>
  
  <script src="javascripts/jquery.foundation.navigation.js"></script>
  
  <script src="javascripts/jquery.foundation.buttons.js"></script>
  
  <script src="javascripts/jquery.foundation.tabs.js"></script>
  
  <script src="javascripts/jquery.foundation.tooltips.js"></script>
  
  <script src="javascripts/jquery.foundation.accordion.js"></script>
  
  <script src="javascripts/jquery.placeholder.js"></script>
  
  <script src="javascripts/jquery.foundation.alerts.js"></script>
  
  -->
  
  <!-- Included JS Files (Compressed) -->
  <script src="/public/home/javascripts/jquery.js"></script>
  <script src="/public/home/javascripts/foundation.min.js"></script>
  
  <!-- Initialize JS Plugins -->
  <script src="/public/home/javascripts/app.js"></script>
</body>
</html>
