<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Frameset//EN">
<HTML><HEAD><TITLE>pt影视中心--后台管理</TITLE>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
	<SCRIPT language=JavaScript>
		window.self.focus();
	</SCRIPT>
<META content="MSHTML 6.00.6000.16890" name=GENERATOR>
</HEAD>
<FRAMESET border=0 frameSpacing=0 frameBorder=0 cols=180,*><FRAME name=menu src="/admin/navi" scrolling=yes>
<FRAME name=main src="/admin/videoclass" 
scrolling=yes>
<NOFRAMES></NOFRAMES>
</FRAMESET>
</HTML>
