<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>后台管理</TITLE>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<META content=Alan name=Author><LINK rev=MADE
href="mailto:haowubai@hotmail.com"><LINK href="/public/admin/stylesheets/private.css"
type=text/css rel=stylesheet>
<META content="MSHTML 6.00.6000.16890" name=GENERATOR></HEAD>
<BODY>
<TABLE class=navi cellSpacing=1 align=center border=0>
  <TBODY>
  <TR>

  <form action="/admin/updatepass" method="post" >

    <TH>后台 >> 修改密码</TH></TR></TBODY></TABLE><BR>

	<table border=0 cellspacing=1 align=center class=form>
	<tr>
		<th colspan="2">用户密码修改</th>
	</tr>
     	  <tr>
  <td align="right">用户名:</td>
  <td><input type="text" name="uname" size=35/>  </td>
  </tr>
       	  <tr>
  <td align="right">原密码:</td>
  <td><input type="password" name="passw" size=35 />  </td>
  </tr>
         	  <tr>
  <td align="right">新密码:</td>
  <td><input type="password" name="passnw" size=35/>  </td>
  </tr>
  
  <tr>
    <td colspan="2" align="center" height='30'>
  <input type="submit"  target='_parent' name="update" onclick="return confirm('提示：您确定要修改密码吗？')" value=" 确认 "/>

  </td></form>
    </tr>
	</table>
	</BODY></HTML>