<?php
$paginated = function ($page,$num,$size){
    $half = intval($size / 2); 
    $page_start = max(1, $page - $half); 
    $page_end = min($page_start + $size - 1, $num);
    $page_start = max(1, $page_end - $size + 1);
    return array($page_start,$page_end);
};
?> 
  <header class="topbar">
    <div class="logo">
      <a href="http://pt.jmu.edu.cn"><img src="/public/home/images/logo.png" />有源网</a>
    </div>
    <ul class="user">
      <li><a href="#"><?php echo $userInfo['username'];?></a></li>
      <li><a href="/message<?php if($userInfo['new_msg']) echo '?update=1';?>"><i class="icon-envelope-alt"></i></a></li>
      <?php if($userInfo['is_admin']): ?>
      <li><a href="/manage/">管理</a></li>
      <?php endif;?>
      <li><a href="/logout">退出</a></li>
    </ul>
    <?php if($userInfo['new_msg']): ?>
    <div class="tips"><a href="/message">你有<?php echo $userInfo['new_msg'];?>条新消息</a></div>
    <?php endif;?>
    <nav class="top-nav">
      <ul>
      <?php $style = $current_class?'':'class="selected"';?>
      <li <?php echo $style;?>><a href="/"><div class="icon-home"></div>有源主页</a></li>
      <?php foreach ($classList as $class):
        $style = ($current_class && $current_class == $class)?'class="selected"':'';
      ?>
        <li <?php echo $style;?>><a href="/?id=<?php echo $class;?>"><div class="icon-play-circle"></div><?php echo $classInfo[$class][0];?></a></li>
      <?php endforeach;?>
      </ul>
    </nav>
    <div class="search">
      <input id="search" type="text" value="搜索视频"><a class="button" id="index_search"><div class="icon-search"></div>搜索</a>
    </div>
  </header>
  <section class="container">
    <div class="row" id="videos0">
      <div class="title red"><?php echo $classInfo[$current_class][0];?><a href="javascript:toggleSlie(0);" class="sh-block">收起</a></div>
      <ul class="detail">
      <?php foreach ($videos as $video): ?>
        <li class="four columns">
          <div class="video-pic">
            <a href="/play/<?php echo $video['fid'];?>">
              <img src="/public/upload/thumb_img/<?php echo $video['uimgfile'];?>" /></a>
          </div>
          <div class="video-info">
            <a href="/play/<?php echo $video['fid'];?>"><?php echo $video['ftitle'];?></a>
            <div class="level">
              评级：
            <?php
              $score = (int)$video['score']/($video['votes']?:1);  
              for($i = 0;$i<$score;$i++):
            ?>
              <img src="/public/home/images/star_red.gif">
            <?php endfor;?>
            <?php for($i = $score;$i<5;$i++):?>
              <img src="/public/home/images/star_grey.gif">
            <?php endfor;?>       
            </div>
            <time class="added">Added: <?php echo strftime("%Y-%m-%d",$video['addtime']);?></time>
          </div>
        </li>
      <?php endforeach;?>
      </ul>
    </div>
	<div class="page row">
      <ul>
        <?php
          list($page_start,$page_end) = $paginated($page,$pages,5);
        ?>
          <li><a href="?page=<?php echo ($page_start>1)?$page_start-1:1;?>" class="prev">前一页</a></li>
        <?php 
          for ($i=$page_start; $i<=$page_end; $i++): 
            $style = ($i == $page)?'class="selected"':"";
        ?>
          <li <?php echo $style;?>><a href="?page=<?php echo $i;?>"><?php echo $i;?></a></li>
        <?php endfor;?>
        <li><a href="?page=<?php echo ($page_end>=$pages)?$page_end:$page_end+1;?>" class="next">后一页</a></li>
      </ul>
    </div>
  </section>
  <div class="gotop" onclick="scroll(0,0);">
    <div class="icon-arrow-up"></div>
    <span>返回顶部</span>
  </div>
  <footer>
    <p>(c)<a href="http://pt.jmu.edu.cn">有源pt影视中心</a>2012-2013 Powered by <a href="#">集美大学网络性能测试小组</a></p>
    <p>维护:集美大学网络开发小组&理学院网络协会</p>
  </footer>


  
  <!-- Included JS Files (Uncompressed) -->
  <!--
  
  <script src="javascripts/jquery.js"></script>
  
  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>
  
  <script src="javascripts/jquery.foundation.forms.js"></script>
  
  <script src="javascripts/jquery.foundation.reveal.js"></script>
  
  <script src="javascripts/jquery.foundation.orbit.js"></script>
  
  <script src="javascripts/jquery.foundation.navigation.js"></script>
  
  <script src="javascripts/jquery.foundation.buttons.js"></script>
  
  <script src="javascripts/jquery.foundation.tabs.js"></script>
  
  <script src="javascripts/jquery.foundation.tooltips.js"></script>
  
  <script src="javascripts/jquery.foundation.accordion.js"></script>
  
  <script src="javascripts/jquery.placeholder.js"></script>
  
  <script src="javascripts/jquery.foundation.alerts.js"></script>
  
  -->
  
  <script src="/public/home/javascripts/jsjquery.comments.js"></script>
  
