<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
<meta name='Author' content='Alan'>
<link rev=MADE href='mailto:haowubai@hotmail.com'><title>pt影视中心--后台管理</title>
<link rel='stylesheet' type='text/css' href='/public/admin/stylesheets/private.css'>

</head><body>
	<br><br><br>
	  <form method="post">
	<table border=0 cellspacing=1 align=center class=form>
	<tr>
		<th colspan="2">用户登录</th>
	</tr>
     	  <tr>
  <td align="right">登录用户:</td>
  <td><input type="text" name="name" value="" size="20" maxlength="40"/>  </td>
  </tr>
       	  <tr>
  <td align="right">登录密码:</td>
  <td><input type="password" name="pass" value="" size="20" maxlength="40"/>  </td>
  </tr>
  <tr>
    <td colspan="2" align="center" height='30'>
  <input type="submit" name="update" value=" 登录 "/>

  </td>  </form>
    </tr>
	</table>
</body></html>
